table Sensitivity
	lineageTag: 79f82b50-09d3-44d4-b4d2-074dea11d440

	measure 'Scenario Positive Breadth' = SELECTEDVALUE('Sensitivity'[Positive Breadth Value])
		formatString: 0.0"%"
		lineageTag: aa78b869-1aac-4eb0-9fd8-39335fb500e8

	measure 'Scenario Median Movement' = SELECTEDVALUE('Sensitivity'[Median Movement Value])
		formatString: 0.000
		lineageTag: dc3f9704-5e0d-49a0-96bc-297306c13300

	measure 'Difference from Primary' = SELECTEDVALUE('Sensitivity'[Difference from Primary Value])
		formatString: 0.0" pp"
		lineageTag: fa2ba294-b337-48f3-9698-9a11c57e6154

	measure 'Scenario Eligible Units' = SELECTEDVALUE('Sensitivity'[Eligible Unit Count])
		formatString: #,0
		lineageTag: 4c2fc434-8062-46df-b511-f18601adefce

	column 'Broad Product Category'
		dataType: string
		lineageTag: 8de54de7-7467-4eb3-aebd-288ae8bd22a7
		sourceColumn: broad_product_category

	column 'Evidence Sufficiency Tier'
		dataType: string
		lineageTag: 99da1737-6470-458a-88f9-788a9722d6d3
		sourceColumn: evidence_sufficiency_tier

	column 'Sensitivity Status'
		dataType: string
		lineageTag: a114dfdd-4088-4eb4-91f3-2225e06d6cdb
		sourceColumn: sensitivity_status

	column 'Sensitivity Scenario'
		dataType: string
		lineageTag: 8975b441-af21-466a-a86d-7c9c53975feb
		sourceColumn: sensitivity_scenario

	column 'Unit of Analysis'
		dataType: string
		lineageTag: 95156786-f2f1-402e-94eb-f3e287001b1a
		sourceColumn: unit_of_analysis

	column 'Eligible Unit Count'
		dataType: int64
		lineageTag: 263a7bf4-11a5-4700-b980-62428c0421ac
		sourceColumn: eligible_unit_count

	column 'Positive Unit Count'
		dataType: int64
		lineageTag: dee1f02d-47fe-4a75-b735-6498e2a733d0
		sourceColumn: positive_unit_count

	column 'Zero Unit Count'
		dataType: int64
		lineageTag: 050e7152-8841-49e9-9779-bf4f519252a3
		sourceColumn: zero_unit_count

	column 'Negative Unit Count'
		dataType: int64
		lineageTag: 1476249a-0bae-467d-89b0-84d83604884b
		sourceColumn: negative_unit_count

	column 'Positive Breadth Value'
		dataType: double
		lineageTag: ddcdf03f-b404-4f88-94e2-3c9e3a9decf2
		sourceColumn: positive_favorite_movement_breadth

	column 'Median Movement Value'
		dataType: double
		lineageTag: 3155517c-ed98-4f62-a559-c87016a4fe0f
		sourceColumn: median_daily_favorite_movement

	column 'Difference from Primary Value'
		dataType: double
		lineageTag: 7329e0e0-9618-4686-b045-60a2066138a6
		sourceColumn: breadth_difference_from_primary_percentage_points

	column 'Interpretation Note'
		dataType: string
		lineageTag: 40fd0395-41b1-46da-bb94-77f1007a3453
		sourceColumn: interpretation_note

	column 'Scenario Display' = SWITCH('Sensitivity'[Sensitivity Scenario], "PRIMARY_EXACT_PRODUCT", "PRIMARY — exact displays", "COMPACT_INCLUSIVE_PRODUCT", "SENSITIVITY — compact inclusive", "OUTLIER_EXCLUDED_PRODUCT", "SENSITIVITY — outlier excluded", "INTERVAL_WEIGHTED_EXACT", "SENSITIVITY — interval weighted", 'Sensitivity'[Sensitivity Scenario])
		dataType: string
		lineageTag: 318b2f3d-2e73-487c-a8a2-848813279fa1

	column 'Scenario Type' = IF('Sensitivity'[Sensitivity Scenario] = "PRIMARY_EXACT_PRODUCT", "PRIMARY", "SENSITIVITY")
		dataType: string
		lineageTag: 259e6689-71d4-486c-b5d8-1afa6e379d72

	column crosses_50_percent_reference_flag
		dataType: string
		lineageTag: 2557dcee-6996-4f03-bc2b-ec13ac5b55d9
		summarizeBy: none
		sourceColumn: crosses_50_percent_reference_flag

		annotation SummarizationSetBy = Automatic

	column median_direction_change_flag
		dataType: string
		lineageTag: 0edb2f18-d2fc-4f9d-a4a9-422498d02589
		summarizeBy: none
		sourceColumn: median_direction_change_flag

		annotation SummarizationSetBy = Automatic

	column breadth_difference_over_10pp_flag
		dataType: string
		lineageTag: 88fb04a7-a80c-4793-bf64-2e95c1f84956
		summarizeBy: none
		sourceColumn: breadth_difference_over_10pp_flag

		annotation SummarizationSetBy = Automatic

	column material_conflict_flag
		dataType: string
		lineageTag: 16041e4e-1bfc-4d0d-a8aa-3e6385d89340
		summarizeBy: none
		sourceColumn: material_conflict_flag

		annotation SummarizationSetBy = Automatic

	column publishable_movement_flag
		dataType: string
		lineageTag: 7f83c13f-8d41-4bc6-bcc1-a47844866d00
		summarizeBy: none
		sourceColumn: publishable_movement_flag

		annotation SummarizationSetBy = Automatic

	partition Sensitivity = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.FromText("YnJvYWRfcHJvZHVjdF9jYXRlZ29yeSxldmlkZW5jZV9zdWZmaWNpZW5jeV90aWVyLHNlbnNpdGl2aXR5X3N0YXR1cyxzZW5zaXRpdml0eV9zY2VuYXJpbyx1bml0X29mX2FuYWx5c2lzLGVsaWdpYmxlX3VuaXRfY291bnQscG9zaXRpdmVfdW5pdF9jb3VudCx6ZXJvX3VuaXRfY291bnQsbmVnYXRpdmVfdW5pdF9jb3VudCxwb3NpdGl2ZV9mYXZvcml0ZV9tb3ZlbWVudF9icmVhZHRoLG1lZGlhbl9kYWlseV9mYXZvcml0ZV9tb3ZlbWVudCxicmVhZHRoX2RpZmZlcmVuY2VfZnJvbV9wcmltYXJ5X3BlcmNlbnRhZ2VfcG9pbnRzLGNyb3NzZXNfNTBfcGVyY2VudF9yZWZlcmVuY2VfZmxhZyxtZWRpYW5fZGlyZWN0aW9uX2NoYW5nZV9mbGFnLGJyZWFkdGhfZGlmZmVyZW5jZV9vdmVyXzEwcHBfZmxhZyxtYXRlcmlhbF9jb25mbGljdF9mbGFnLHB1Ymxpc2hhYmxlX21vdmVtZW50X2ZsYWcsaW50ZXJwcmV0YXRpb25fbm90ZQpBdXRvbW90aXZlLE1PREVSQVRFLFJPQlVTVCxQUklNQVJZX0VYQUNUX1BST0RVQ1QscHJvZHVjdCw5Niw0NSw0OSwyLDQ2Ljg3NSwwLDAsRmFsc2UsRmFsc2UsRmFsc2UsRmFsc2UsVHJ1ZSxQcmltYXJ5IGdvdmVybmVkIEtQSQpBdXRvbW90aXZlLE1PREVSQVRFLFJPQlVTVCxDT01QQUNUX0lOQ0xVU0lWRV9QUk9EVUNULHByb2R1Y3QsMTI2LDUyLDcyLDIsNDEuMjY5ODQxMjcsMCwtNS42MDUxNTg3MyxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCkF1dG9tb3RpdmUsTU9ERVJBVEUsUk9CVVNULE9VVExJRVJfRVhDTFVERURfUFJPRFVDVCxwcm9kdWN0LDk2LDQ1LDQ5LDIsNDYuODc1LDAsMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCkF1dG9tb3RpdmUsTU9ERVJBVEUsUk9CVVNULElOVEVSVkFMX1dFSUdIVEVEX0VYQUNULGludGVydmFsLDExOCw0OSw2NywyLDQxLjUyNTQyMzczLDAsLTUuMzQ5NTc2MjcxLEZhbHNlLEZhbHNlLEZhbHNlLEZhbHNlLFRydWUsU2Vuc2l0aXZpdHkgcmVtYWlucyB3aXRoaW4gUGhhc2UgNiBjb25mbGljdCBsaW1pdHMKQmFieSAmIEtpZHMsTU9ERVJBVEUsVU5TVEFCTEUsUFJJTUFSWV9FWEFDVF9QUk9EVUNULHByb2R1Y3QsMTQ4LDc3LDY5LDIsNTIuMDI3MDI3MDMsMC4xNDI4NTcxNDI5LDAsRmFsc2UsRmFsc2UsRmFsc2UsRmFsc2UsVHJ1ZSxQcmltYXJ5IGdvdmVybmVkIEtQSQpCYWJ5ICYgS2lkcyxNT0RFUkFURSxVTlNUQUJMRSxDT01QQUNUX0lOQ0xVU0lWRV9QUk9EVUNULHByb2R1Y3QsMTkwLDg2LDEwMiwyLDQ1LjI2MzE1Nzg5LDAsLTYuNzYzODY5MTMyLFRydWUsVHJ1ZSxGYWxzZSxUcnVlLFRydWUsU2Vuc2l0aXZpdHkgaGFzIGEgUGhhc2UgNiBtYXRlcmlhbCBjb25mbGljdApCYWJ5ICYgS2lkcyxNT0RFUkFURSxVTlNUQUJMRSxPVVRMSUVSX0VYQ0xVREVEX1BST0RVQ1QscHJvZHVjdCwxNDgsNzcsNjksMiw1Mi4wMjcwMjcwMywwLjE0Mjg1NzE0MjksMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCkJhYnkgJiBLaWRzLE1PREVSQVRFLFVOU1RBQkxFLElOVEVSVkFMX1dFSUdIVEVEX0VYQUNULGludGVydmFsLDE2Myw4NCw3NywyLDUxLjUzMzc0MjMzLDAuMTQyODU3MTQyOSwtMC40OTMyODQ2OTU3LEZhbHNlLEZhbHNlLEZhbHNlLEZhbHNlLFRydWUsU2Vuc2l0aXZpdHkgcmVtYWlucyB3aXRoaW4gUGhhc2UgNiBjb25mbGljdCBsaW1pdHMKRW50ZXJ0YWlubWVudCAmIEhvYmJpZXMsSU5TVUZGSUNJRU5ULE5PVF9BU1NFU1NBQkxFX0lOU1VGRklDSUVOVF9FVklERU5DRSxQUklNQVJZX0VYQUNUX1BST0RVQ1QscHJvZHVjdCwxOSwxNiwzLDAsLCwsLCwsLEZhbHNlLE1vdmVtZW50IHZhbHVlcyBzdXBwcmVzc2VkIGJlY2F1c2UgZXZpZGVuY2UgaXMgaW5zdWZmaWNpZW50CkVudGVydGFpbm1lbnQgJiBIb2JiaWVzLElOU1VGRklDSUVOVCxOT1RfQVNTRVNTQUJMRV9JTlNVRkZJQ0lFTlRfRVZJREVOQ0UsQ09NUEFDVF9JTkNMVVNJVkVfUFJPRFVDVCxwcm9kdWN0LDIyLDE2LDYsMCwsLCwsLCwsRmFsc2UsTW92ZW1lbnQgdmFsdWVzIHN1cHByZXNzZWQgYmVjYXVzZSBldmlkZW5jZSBpcyBpbnN1ZmZpY2llbnQKRW50ZXJ0YWlubWVudCAmIEhvYmJpZXMsSU5TVUZGSUNJRU5ULE5PVF9BU1NFU1NBQkxFX0lOU1VGRklDSUVOVF9FVklERU5DRSxPVVRMSUVSX0VYQ0xVREVEX1BST0RVQ1QscHJvZHVjdCwxOSwxNiwzLDAsLCwsLCwsLEZhbHNlLE1vdmVtZW50IHZhbHVlcyBzdXBwcmVzc2VkIGJlY2F1c2UgZXZpZGVuY2UgaXMgaW5zdWZmaWNpZW50CkVudGVydGFpbm1lbnQgJiBIb2JiaWVzLElOU1VGRklDSUVOVCxOT1RfQVNTRVNTQUJMRV9JTlNVRkZJQ0lFTlRfRVZJREVOQ0UsSU5URVJWQUxfV0VJR0hURURfRVhBQ1QsaW50ZXJ2YWwsMjAsMTcsMywwLCwsLCwsLCxGYWxzZSxNb3ZlbWVudCB2YWx1ZXMgc3VwcHJlc3NlZCBiZWNhdXNlIGV2aWRlbmNlIGlzIGluc3VmZmljaWVudApGYXNoaW9uLEhJR0gsVU5TVEFCTEUsUFJJTUFSWV9FWEFDVF9QUk9EVUNULHByb2R1Y3QsODgxLDQ2MywzOTQsMjQsNTIuNTUzOTE2LDAuMDkwOTA5MDkwOTEsMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFByaW1hcnkgZ292ZXJuZWQgS1BJCkZhc2hpb24sSElHSCxVTlNUQUJMRSxDT01QQUNUX0lOQ0xVU0lWRV9QUk9EVUNULHByb2R1Y3QsMTE1NCw1MjIsNjA4LDI0LDQ1LjIzMzk2ODgsMCwtNy4zMTk5NDcyLFRydWUsVHJ1ZSxGYWxzZSxUcnVlLFRydWUsU2Vuc2l0aXZpdHkgaGFzIGEgUGhhc2UgNiBtYXRlcmlhbCBjb25mbGljdApGYXNoaW9uLEhJR0gsVU5TVEFCTEUsT1VUTElFUl9FWENMVURFRF9QUk9EVUNULHByb2R1Y3QsODgxLDQ2MywzOTQsMjQsNTIuNTUzOTE2LDAuMDkwOTA5MDkwOTEsMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCkZhc2hpb24sSElHSCxVTlNUQUJMRSxJTlRFUlZBTF9XRUlHSFRFRF9FWEFDVCxpbnRlcnZhbCwxMDc3LDUyNSw1MTksMzMsNDguNzQ2NTE4MTEsMCwtMy44MDczOTc4OTksVHJ1ZSxUcnVlLEZhbHNlLFRydWUsVHJ1ZSxTZW5zaXRpdml0eSBoYXMgYSBQaGFzZSA2IG1hdGVyaWFsIGNvbmZsaWN0Ckdyb2NlcmllcyAmIFBldHMsSElHSCxESVJFQ1RJT05BTExZX1NUQUJMRSxQUklNQVJZX0VYQUNUX1BST0RVQ1QscHJvZHVjdCwxMTIsNzIsMzUsNSw2NC4yODU3MTQyOSwwLjIxMTExMTExMTEsMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFByaW1hcnkgZ292ZXJuZWQgS1BJCkdyb2NlcmllcyAmIFBldHMsSElHSCxESVJFQ1RJT05BTExZX1NUQUJMRSxDT01QQUNUX0lOQ0xVU0lWRV9QUk9EVUNULHByb2R1Y3QsMTQ2LDc4LDYzLDUsNTMuNDI0NjU3NTMsMC4wOTU0NTQ1NDU0NSwtMTAuODYxMDU2NzUsRmFsc2UsRmFsc2UsVHJ1ZSxUcnVlLFRydWUsU2Vuc2l0aXZpdHkgaGFzIGEgUGhhc2UgNiBtYXRlcmlhbCBjb25mbGljdApHcm9jZXJpZXMgJiBQZXRzLEhJR0gsRElSRUNUSU9OQUxMWV9TVEFCTEUsT1VUTElFUl9FWENMVURFRF9QUk9EVUNULHByb2R1Y3QsMTEyLDcyLDM1LDUsNjQuMjg1NzE0MjksMC4yMTExMTExMTExLDAsRmFsc2UsRmFsc2UsRmFsc2UsRmFsc2UsVHJ1ZSxTZW5zaXRpdml0eSByZW1haW5zIHdpdGhpbiBQaGFzZSA2IGNvbmZsaWN0IGxpbWl0cwpHcm9jZXJpZXMgJiBQZXRzLEhJR0gsRElSRUNUSU9OQUxMWV9TVEFCTEUsSU5URVJWQUxfV0VJR0hURURfRVhBQ1QsaW50ZXJ2YWwsMTI1LDc4LDQyLDUsNjIuNCwwLjIsLTEuODg1NzE0Mjg2LEZhbHNlLEZhbHNlLEZhbHNlLEZhbHNlLFRydWUsU2Vuc2l0aXZpdHkgcmVtYWlucyB3aXRoaW4gUGhhc2UgNiBjb25mbGljdCBsaW1pdHMKSGVhbHRoICYgQmVhdXR5LE1PREVSQVRFLFJPQlVTVCxQUklNQVJZX0VYQUNUX1BST0RVQ1QscHJvZHVjdCwzMzcsMjEyLDExNCwxMSw2Mi45MDgwMTE4NywwLjE2NjY2NjY2NjcsMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFByaW1hcnkgZ292ZXJuZWQgS1BJCkhlYWx0aCAmIEJlYXV0eSxNT0RFUkFURSxST0JVU1QsQ09NUEFDVF9JTkNMVVNJVkVfUFJPRFVDVCxwcm9kdWN0LDQzNiwyMzQsMTkxLDExLDUzLjY2OTcyNDc3LDAuMDkwOTA5MDkwOTEsLTkuMjM4Mjg3MDk5LEZhbHNlLEZhbHNlLEZhbHNlLEZhbHNlLFRydWUsU2Vuc2l0aXZpdHkgcmVtYWlucyB3aXRoaW4gUGhhc2UgNiBjb25mbGljdCBsaW1pdHMKSGVhbHRoICYgQmVhdXR5LE1PREVSQVRFLFJPQlVTVCxPVVRMSUVSX0VYQ0xVREVEX1BST0RVQ1QscHJvZHVjdCwzMzcsMjEyLDExNCwxMSw2Mi45MDgwMTE4NywwLjE2NjY2NjY2NjcsMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCkhlYWx0aCAmIEJlYXV0eSxNT0RFUkFURSxST0JVU1QsSU5URVJWQUxfV0VJR0hURURfRVhBQ1QsaW50ZXJ2YWwsNDExLDIzOSwxNjAsMTIsNTguMTUwODUxNTgsMC4xNTM4NDYxNTM4LC00Ljc1NzE2MDI4OCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCkhvbWUsSElHSCxVTlNUQUJMRSxQUklNQVJZX0VYQUNUX1BST0RVQ1QscHJvZHVjdCwxOTQsMTExLDc2LDcsNTcuMjE2NDk0ODUsMC4xNzE1Njg2Mjc1LDAsRmFsc2UsRmFsc2UsRmFsc2UsRmFsc2UsVHJ1ZSxQcmltYXJ5IGdvdmVybmVkIEtQSQpIb21lLEhJR0gsVU5TVEFCTEUsQ09NUEFDVF9JTkNMVVNJVkVfUFJPRFVDVCxwcm9kdWN0LDMyMywxNTAsMTY2LDcsNDYuNDM5NjI4NDgsMCwtMTAuNzc2ODY2MzYsVHJ1ZSxUcnVlLFRydWUsVHJ1ZSxUcnVlLFNlbnNpdGl2aXR5IGhhcyBhIFBoYXNlIDYgbWF0ZXJpYWwgY29uZmxpY3QKSG9tZSxISUdILFVOU1RBQkxFLE9VVExJRVJfRVhDTFVERURfUFJPRFVDVCxwcm9kdWN0LDE5NCwxMTEsNzYsNyw1Ny4yMTY0OTQ4NSwwLjE3MTU2ODYyNzUsMCxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCkhvbWUsSElHSCxVTlNUQUJMRSxJTlRFUlZBTF9XRUlHSFRFRF9FWEFDVCxpbnRlcnZhbCwyMjEsMTE5LDkzLDksNTMuODQ2MTUzODUsMC4xMzMzMzMzMzMzLC0zLjM3MDM0MDk5OSxGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzCk1vYmlsZSAmIFRlY2hub2xvZ3ksSElHSCxVTlNUQUJMRSxQUklNQVJZX0VYQUNUX1BST0RVQ1QscHJvZHVjdCwzMDQsMTU5LDEzMSwxNCw1Mi4zMDI2MzE1OCwwLjA4MzMzMzMzMzMzLDAsRmFsc2UsRmFsc2UsRmFsc2UsRmFsc2UsVHJ1ZSxQcmltYXJ5IGdvdmVybmVkIEtQSQpNb2JpbGUgJiBUZWNobm9sb2d5LEhJR0gsVU5TVEFCTEUsQ09NUEFDVF9JTkNMVVNJVkVfUFJPRFVDVCxwcm9kdWN0LDQxNCwxODUsMjE1LDE0LDQ0LjY4NTk5MDM0LDAsLTcuNjE2NjQxMjQxLFRydWUsVHJ1ZSxGYWxzZSxUcnVlLFRydWUsU2Vuc2l0aXZpdHkgaGFzIGEgUGhhc2UgNiBtYXRlcmlhbCBjb25mbGljdApNb2JpbGUgJiBUZWNobm9sb2d5LEhJR0gsVU5TVEFCTEUsT1VUTElFUl9FWENMVURFRF9QUk9EVUNULHByb2R1Y3QsMzA0LDE1OSwxMzEsMTQsNTIuMzAyNjMxNTgsMC4wODMzMzMzMzMzMywwLEZhbHNlLEZhbHNlLEZhbHNlLEZhbHNlLFRydWUsU2Vuc2l0aXZpdHkgcmVtYWlucyB3aXRoaW4gUGhhc2UgNiBjb25mbGljdCBsaW1pdHMKTW9iaWxlICYgVGVjaG5vbG9neSxISUdILFVOU1RBQkxFLElOVEVSVkFMX1dFSUdIVEVEX0VYQUNULGludGVydmFsLDM3MywxODQsMTczLDE2LDQ5LjMyOTc1ODcxLDAsLTIuOTcyODcyODY2LFRydWUsVHJ1ZSxGYWxzZSxUcnVlLFRydWUsU2Vuc2l0aXZpdHkgaGFzIGEgUGhhc2UgNiBtYXRlcmlhbCBjb25mbGljdApPdGhlcnMsSU5TVUZGSUNJRU5ULE5PVF9BU1NFU1NBQkxFX0lOU1VGRklDSUVOVF9FVklERU5DRSxQUklNQVJZX0VYQUNUX1BST0RVQ1QscHJvZHVjdCwwLDAsMCwwLCwsLCwsLCxGYWxzZSxNb3ZlbWVudCB2YWx1ZXMgc3VwcHJlc3NlZCBiZWNhdXNlIGV2aWRlbmNlIGlzIGluc3VmZmljaWVudApPdGhlcnMsSU5TVUZGSUNJRU5ULE5PVF9BU1NFU1NBQkxFX0lOU1VGRklDSUVOVF9FVklERU5DRSxDT01QQUNUX0lOQ0xVU0lWRV9QUk9EVUNULHByb2R1Y3QsMCwwLDAsMCwsLCwsLCwsRmFsc2UsTW92ZW1lbnQgdmFsdWVzIHN1cHByZXNzZWQgYmVjYXVzZSBldmlkZW5jZSBpcyBpbnN1ZmZpY2llbnQKT3RoZXJzLElOU1VGRklDSUVOVCxOT1RfQVNTRVNTQUJMRV9JTlNVRkZJQ0lFTlRfRVZJREVOQ0UsT1VUTElFUl9FWENMVURFRF9QUk9EVUNULHByb2R1Y3QsMCwwLDAsMCwsLCwsLCwsRmFsc2UsTW92ZW1lbnQgdmFsdWVzIHN1cHByZXNzZWQgYmVjYXVzZSBldmlkZW5jZSBpcyBpbnN1ZmZpY2llbnQKT3RoZXJzLElOU1VGRklDSUVOVCxOT1RfQVNTRVNTQUJMRV9JTlNVRkZJQ0lFTlRfRVZJREVOQ0UsSU5URVJWQUxfV0VJR0hURURfRVhBQ1QsaW50ZXJ2YWwsMCwwLDAsMCwsLCwsLCwsRmFsc2UsTW92ZW1lbnQgdmFsdWVzIHN1cHByZXNzZWQgYmVjYXVzZSBldmlkZW5jZSBpcyBpbnN1ZmZpY2llbnQKU3BvcnRzICYgT3V0ZG9vcixNT0RFUkFURSxST0JVU1QsUFJJTUFSWV9FWEFDVF9QUk9EVUNULHByb2R1Y3QsNjcsMzEsMzUsMSw0Ni4yNjg2NTY3MiwwLDAsRmFsc2UsRmFsc2UsRmFsc2UsRmFsc2UsVHJ1ZSxQcmltYXJ5IGdvdmVybmVkIEtQSQpTcG9ydHMgJiBPdXRkb29yLE1PREVSQVRFLFJPQlVTVCxDT01QQUNUX0lOQ0xVU0lWRV9QUk9EVUNULHByb2R1Y3QsODcsMzQsNTIsMSwzOS4wODA0NTk3NywwLC03LjE4ODE5Njk0NixGYWxzZSxGYWxzZSxGYWxzZSxGYWxzZSxUcnVlLFNlbnNpdGl2aXR5IHJlbWFpbnMgd2l0aGluIFBoYXNlIDYgY29uZmxpY3QgbGltaXRzClNwb3J0cyAmIE91dGRvb3IsTU9ERVJBVEUsUk9CVVNULE9VVExJRVJfRVhDTFVERURfUFJPRFVDVCxwcm9kdWN0LDY3LDMxLDM1LDEsNDYuMjY4NjU2NzIsMCwwLEZhbHNlLEZhbHNlLEZhbHNlLEZhbHNlLFRydWUsU2Vuc2l0aXZpdHkgcmVtYWlucyB3aXRoaW4gUGhhc2UgNiBjb25mbGljdCBsaW1pdHMKU3BvcnRzICYgT3V0ZG9vcixNT0RFUkFURSxST0JVU1QsSU5URVJWQUxfV0VJR0hURURfRVhBQ1QsaW50ZXJ2YWwsNzEsMzMsMzcsMSw0Ni40Nzg4NzMyNCwwLDAuMjEwMjE2NTIzLEZhbHNlLEZhbHNlLEZhbHNlLEZhbHNlLFRydWUsU2Vuc2l0aXZpdHkgcmVtYWlucyB3aXRoaW4gUGhhc2UgNiBjb25mbGljdCBsaW1pdHMKVGlja2V0cyAmIFZvdWNoZXJzLElOU1VGRklDSUVOVCxOT1RfQVNTRVNTQUJMRV9JTlNVRkZJQ0lFTlRfRVZJREVOQ0UsUFJJTUFSWV9FWEFDVF9QUk9EVUNULHByb2R1Y3QsMywyLDEsMCwsLCwsLCwsRmFsc2UsTW92ZW1lbnQgdmFsdWVzIHN1cHByZXNzZWQgYmVjYXVzZSBldmlkZW5jZSBpcyBpbnN1ZmZpY2llbnQKVGlja2V0cyAmIFZvdWNoZXJzLElOU1VGRklDSUVOVCxOT1RfQVNTRVNTQUJMRV9JTlNVRkZJQ0lFTlRfRVZJREVOQ0UsQ09NUEFDVF9JTkNMVVNJVkVfUFJPRFVDVCxwcm9kdWN0LDMsMiwxLDAsLCwsLCwsLEZhbHNlLE1vdmVtZW50IHZhbHVlcyBzdXBwcmVzc2VkIGJlY2F1c2UgZXZpZGVuY2UgaXMgaW5zdWZmaWNpZW50ClRpY2tldHMgJiBWb3VjaGVycyxJTlNVRkZJQ0lFTlQsTk9UX0FTU0VTU0FCTEVfSU5TVUZGSUNJRU5UX0VWSURFTkNFLE9VVExJRVJfRVhDTFVERURfUFJPRFVDVCxwcm9kdWN0LDMsMiwxLDAsLCwsLCwsLEZhbHNlLE1vdmVtZW50IHZhbHVlcyBzdXBwcmVzc2VkIGJlY2F1c2UgZXZpZGVuY2UgaXMgaW5zdWZmaWNpZW50ClRpY2tldHMgJiBWb3VjaGVycyxJTlNVRkZJQ0lFTlQsTk9UX0FTU0VTU0FCTEVfSU5TVUZGSUNJRU5UX0VWSURFTkNFLElOVEVSVkFMX1dFSUdIVEVEX0VYQUNULGludGVydmFsLDMsMiwxLDAsLCwsLCwsLEZhbHNlLE1vdmVtZW50IHZhbHVlcyBzdXBwcmVzc2VkIGJlY2F1c2UgZXZpZGVuY2UgaXMgaW5zdWZmaWNpZW50ClRyYXZlbCxJTlNVRkZJQ0lFTlQsTk9UX0FTU0VTU0FCTEVfSU5TVUZGSUNJRU5UX0VWSURFTkNFLFBSSU1BUllfRVhBQ1RfUFJPRFVDVCxwcm9kdWN0LDgsMiw2LDAsLCwsLCwsLEZhbHNlLE1vdmVtZW50IHZhbHVlcyBzdXBwcmVzc2VkIGJlY2F1c2UgZXZpZGVuY2UgaXMgaW5zdWZmaWNpZW50ClRyYXZlbCxJTlNVRkZJQ0lFTlQsTk9UX0FTU0VTU0FCTEVfSU5TVUZGSUNJRU5UX0VWSURFTkNFLENPTVBBQ1RfSU5DTFVTSVZFX1BST0RVQ1QscHJvZHVjdCw4LDIsNiwwLCwsLCwsLCxGYWxzZSxNb3ZlbWVudCB2YWx1ZXMgc3VwcHJlc3NlZCBiZWNhdXNlIGV2aWRlbmNlIGlzIGluc3VmZmljaWVudApUcmF2ZWwsSU5TVUZGSUNJRU5ULE5PVF9BU1NFU1NBQkxFX0lOU1VGRklDSUVOVF9FVklERU5DRSxPVVRMSUVSX0VYQ0xVREVEX1BST0RVQ1QscHJvZHVjdCw4LDIsNiwwLCwsLCwsLCxGYWxzZSxNb3ZlbWVudCB2YWx1ZXMgc3VwcHJlc3NlZCBiZWNhdXNlIGV2aWRlbmNlIGlzIGluc3VmZmljaWVudApUcmF2ZWwsSU5TVUZGSUNJRU5ULE5PVF9BU1NFU1NBQkxFX0lOU1VGRklDSUVOVF9FVklERU5DRSxJTlRFUlZBTF9XRUlHSFRFRF9FWEFDVCxpbnRlcnZhbCw4LDIsNiwwLCwsLCwsLCxGYWxzZSxNb3ZlbWVudCB2YWx1ZXMgc3VwcHJlc3NlZCBiZWNhdXNlIGV2aWRlbmNlIGlzIGluc3VmZmljaWVudAo=", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Headers, {{"broad_product_category", type text}, {"evidence_sufficiency_tier", type text}, {"sensitivity_status", type text}, {"sensitivity_scenario", type text}, {"unit_of_analysis", type text}, {"eligible_unit_count", Int64.Type}, {"positive_unit_count", Int64.Type}, {"zero_unit_count", Int64.Type}, {"negative_unit_count", Int64.Type}, {"positive_favorite_movement_breadth", type number}, {"median_daily_favorite_movement", type number}, {"breadth_difference_from_primary_percentage_points", type number}, {"interpretation_note", type text}})
				in
				    Types

