{
  "name": "Shopee_Category_Engagement",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "Category Scorecard",
        "columns": [
          {
            "name": "Broad Product Category",
            "dataType": "string",
            "sourceColumn": "broad_product_category"
          },
          {
            "name": "Observed Stable-Category Product Count Value",
            "dataType": "int64",
            "sourceColumn": "observed_stable_category_product_count"
          },
          {
            "name": "Stable Repeated Product Count",
            "dataType": "int64",
            "sourceColumn": "stable_repeated_product_count"
          },
          {
            "name": "Observed Date Count",
            "dataType": "int64",
            "sourceColumn": "observed_date_count"
          },
          {
            "name": "Eligible Exact Interval Count",
            "dataType": "int64",
            "sourceColumn": "eligible_exact_interval_count"
          },
          {
            "name": "Eligible Favorite-Movement Product Count Value",
            "dataType": "int64",
            "sourceColumn": "eligible_favorite_movement_product_count"
          },
          {
            "name": "Positive Product Count",
            "dataType": "int64",
            "sourceColumn": "positive_product_count"
          },
          {
            "name": "Zero Product Count",
            "dataType": "int64",
            "sourceColumn": "zero_product_count"
          },
          {
            "name": "Negative Product Count",
            "dataType": "int64",
            "sourceColumn": "negative_product_count"
          },
          {
            "name": "Breadth Wilson 95% Lower Value",
            "dataType": "double",
            "sourceColumn": "positive_breadth_wilson_95_lower_percent"
          },
          {
            "name": "Breadth Wilson 95% Upper Value",
            "dataType": "double",
            "sourceColumn": "positive_breadth_wilson_95_upper_percent"
          },
          {
            "name": "Breadth Wilson 95% Width Value",
            "dataType": "double",
            "sourceColumn": "positive_breadth_wilson_95_width_percentage_points"
          },
          {
            "name": "Evidence Sufficiency Tier",
            "dataType": "string",
            "sourceColumn": "evidence_sufficiency_tier"
          },
          {
            "name": "Eligible Share of Observed Stable Products",
            "dataType": "double",
            "sourceColumn": "eligible_product_share_of_observed_stable_products_percent"
          },
          {
            "name": "Sensitivity Status",
            "dataType": "string",
            "sourceColumn": "sensitivity_status"
          },
          {
            "name": "Positive Favorite-Movement Breadth Value",
            "dataType": "double",
            "sourceColumn": "positive_favorite_movement_breadth"
          },
          {
            "name": "Median Daily Favorite Movement Value",
            "dataType": "double",
            "sourceColumn": "median_daily_favorite_movement_per_product"
          },
          {
            "name": "Further Investigation Candidate",
            "dataType": "boolean",
            "sourceColumn": "further_investigation_candidate_flag"
          },
          {
            "name": "Analysis Classification",
            "dataType": "string",
            "sourceColumn": "analysis_classification"
          },
          {
            "name": "Breadth-Magnitude Pattern",
            "dataType": "string",
            "sourceColumn": "breadth_magnitude_pattern"
          },
          {
            "name": "Business Interpretation",
            "dataType": "string",
            "sourceColumn": "business_interpretation"
          }
        ],
        "measures": [
          {
            "name": "Observed Stable-Category Product Count",
            "expression": "SUM('Category Scorecard'[Observed Stable-Category Product Count Value])",
            "formatString": "#,0"
          },
          {
            "name": "Eligible Favorite-Movement Product Count",
            "expression": "SUM('Category Scorecard'[Eligible Favorite-Movement Product Count Value])",
            "formatString": "#,0"
          },
          {
            "name": "Positive Favorite-Movement Breadth",
            "expression": "IF(HASONEVALUE('Category Scorecard'[Broad Product Category]), SELECTEDVALUE('Category Scorecard'[Positive Favorite-Movement Breadth Value]), BLANK())",
            "formatString": "0.0\"%\""
          },
          {
            "name": "Median Daily Favorite Movement per Product",
            "expression": "IF(HASONEVALUE('Category Scorecard'[Broad Product Category]), SELECTEDVALUE('Category Scorecard'[Median Daily Favorite Movement Value]), BLANK())",
            "formatString": "0.000"
          },
          {
            "name": "Observed Dates",
            "expression": "SELECTEDVALUE('Category Scorecard'[Observed Date Count])",
            "formatString": "0"
          },
          {
            "name": "Breadth Wilson 95% Lower",
            "expression": "SELECTEDVALUE('Category Scorecard'[Breadth Wilson 95% Lower Value])",
            "formatString": "0.0\"%\""
          },
          {
            "name": "Breadth Wilson 95% Upper",
            "expression": "SELECTEDVALUE('Category Scorecard'[Breadth Wilson 95% Upper Value])",
            "formatString": "0.0\"%\""
          },
          {
            "name": "Breadth Wilson 95% Width",
            "expression": "SELECTEDVALUE('Category Scorecard'[Breadth Wilson 95% Width Value])",
            "formatString": "0.0\" pp\""
          },
          {
            "name": "Broad Product Category Count",
            "expression": "DISTINCTCOUNT('Category Scorecard'[Broad Product Category])",
            "formatString": "0"
          },
          {
            "name": "Publishable Broad Product Category Count",
            "expression": "CALCULATE(DISTINCTCOUNT('Category Scorecard'[Broad Product Category]), 'Category Scorecard'[Evidence Sufficiency Tier] <> \"INSUFFICIENT\")",
            "formatString": "0"
          },
          {
            "name": "Insufficient Broad Product Category Count",
            "expression": "CALCULATE(DISTINCTCOUNT('Category Scorecard'[Broad Product Category]), 'Category Scorecard'[Evidence Sufficiency Tier] = \"INSUFFICIENT\")",
            "formatString": "0"
          },
          {
            "name": "Positive Favorite-Movement Breadth Display",
            "expression": "VAR v=[Positive Favorite-Movement Breadth] RETURN IF(ISBLANK(v), \"N/A — insufficient evidence\", FORMAT(v/100, \"0.0%\"))"
          },
          {
            "name": "Median Daily Favorite Movement Display",
            "expression": "VAR v=[Median Daily Favorite Movement per Product] RETURN IF(ISBLANK(v), \"N/A — insufficient evidence\", FORMAT(v, \"0.000\"))"
          },
          {
            "name": "Eligible Favorite-Movement Product Count Display",
            "expression": "FORMAT([Eligible Favorite-Movement Product Count], \"#,0\")"
          },
          {
            "name": "Evidence Sufficiency Tier Display",
            "expression": "SELECTEDVALUE('Category Scorecard'[Evidence Sufficiency Tier], \"Select one category\")"
          }
        ],
        "partitions": [
          {
            "name": "Category Scorecard",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\projects\\NEW Shopee sales\\outputs\\tables\\phase_7_category_comparison.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Types = Table.TransformColumnTypes(Headers, {{\"broad_product_category\", type text}, {\"observed_stable_category_product_count\", Int64.Type}, {\"stable_repeated_product_count\", Int64.Type}, {\"observed_date_count\", Int64.Type}, {\"eligible_exact_interval_count\", Int64.Type}, {\"eligible_favorite_movement_product_count\", Int64.Type}, {\"positive_product_count\", Int64.Type}, {\"zero_product_count\", Int64.Type}, {\"negative_product_count\", Int64.Type}, {\"positive_breadth_wilson_95_lower_percent\", type number}, {\"positive_breadth_wilson_95_upper_percent\", type number}, {\"positive_breadth_wilson_95_width_percentage_points\", type number}, {\"evidence_sufficiency_tier\", type text}, {\"eligible_product_share_of_observed_stable_products_percent\", type number}, {\"sensitivity_status\", type text}, {\"positive_favorite_movement_breadth\", type number}, {\"median_daily_favorite_movement_per_product\", type number}, {\"further_investigation_candidate_flag\", type logical}, {\"analysis_classification\", type text}, {\"breadth_magnitude_pattern\", type text}, {\"business_interpretation\", type text}})",
                "in",
                "    Types"
              ]
            }
          }
        ]
      },
      {
        "name": "Sensitivity",
        "columns": [
          {
            "name": "Broad Product Category",
            "dataType": "string",
            "sourceColumn": "broad_product_category"
          },
          {
            "name": "Evidence Sufficiency Tier",
            "dataType": "string",
            "sourceColumn": "evidence_sufficiency_tier"
          },
          {
            "name": "Sensitivity Status",
            "dataType": "string",
            "sourceColumn": "sensitivity_status"
          },
          {
            "name": "Sensitivity Scenario",
            "dataType": "string",
            "sourceColumn": "sensitivity_scenario"
          },
          {
            "name": "Unit of Analysis",
            "dataType": "string",
            "sourceColumn": "unit_of_analysis"
          },
          {
            "name": "Eligible Unit Count",
            "dataType": "int64",
            "sourceColumn": "eligible_unit_count"
          },
          {
            "name": "Positive Unit Count",
            "dataType": "int64",
            "sourceColumn": "positive_unit_count"
          },
          {
            "name": "Zero Unit Count",
            "dataType": "int64",
            "sourceColumn": "zero_unit_count"
          },
          {
            "name": "Negative Unit Count",
            "dataType": "int64",
            "sourceColumn": "negative_unit_count"
          },
          {
            "name": "Positive Breadth Value",
            "dataType": "double",
            "sourceColumn": "positive_favorite_movement_breadth"
          },
          {
            "name": "Median Movement Value",
            "dataType": "double",
            "sourceColumn": "median_daily_favorite_movement"
          },
          {
            "name": "Difference from Primary Value",
            "dataType": "double",
            "sourceColumn": "breadth_difference_from_primary_percentage_points"
          },
          {
            "name": "Interpretation Note",
            "dataType": "string",
            "sourceColumn": "interpretation_note"
          },
          {
            "type": "calculated",
            "name": "Scenario Display",
            "dataType": "string",
            "expression": "SWITCH('Sensitivity'[Sensitivity Scenario], \"PRIMARY_EXACT_PRODUCT\", \"PRIMARY — exact displays\", \"COMPACT_INCLUSIVE_PRODUCT\", \"SENSITIVITY — compact inclusive\", \"OUTLIER_EXCLUDED_PRODUCT\", \"SENSITIVITY — outlier excluded\", \"INTERVAL_WEIGHTED_EXACT\", \"SENSITIVITY — interval weighted\", 'Sensitivity'[Sensitivity Scenario])"
          },
          {
            "type": "calculated",
            "name": "Scenario Type",
            "dataType": "string",
            "expression": "IF('Sensitivity'[Sensitivity Scenario] = \"PRIMARY_EXACT_PRODUCT\", \"PRIMARY\", \"SENSITIVITY\")"
          }
        ],
        "measures": [
          {
            "name": "Scenario Positive Breadth",
            "expression": "SELECTEDVALUE('Sensitivity'[Positive Breadth Value])",
            "formatString": "0.0\"%\""
          },
          {
            "name": "Scenario Median Movement",
            "expression": "SELECTEDVALUE('Sensitivity'[Median Movement Value])",
            "formatString": "0.000"
          },
          {
            "name": "Difference from Primary",
            "expression": "SELECTEDVALUE('Sensitivity'[Difference from Primary Value])",
            "formatString": "0.0\" pp\""
          },
          {
            "name": "Scenario Eligible Units",
            "expression": "SELECTEDVALUE('Sensitivity'[Eligible Unit Count])",
            "formatString": "#,0"
          }
        ],
        "partitions": [
          {
            "name": "Sensitivity",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\projects\\NEW Shopee sales\\outputs\\tables\\phase_7_sensitivity_analysis.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Types = Table.TransformColumnTypes(Headers, {{\"broad_product_category\", type text}, {\"evidence_sufficiency_tier\", type text}, {\"sensitivity_status\", type text}, {\"sensitivity_scenario\", type text}, {\"unit_of_analysis\", type text}, {\"eligible_unit_count\", Int64.Type}, {\"positive_unit_count\", Int64.Type}, {\"zero_unit_count\", Int64.Type}, {\"negative_unit_count\", Int64.Type}, {\"positive_favorite_movement_breadth\", type number}, {\"median_daily_favorite_movement\", type number}, {\"breadth_difference_from_primary_percentage_points\", type number}, {\"interpretation_note\", type text}})",
                "in",
                "    Types"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "CategoryScorecard_to_Sensitivity",
        "fromTable": "Sensitivity",
        "fromColumn": "Broad Product Category",
        "toTable": "Category Scorecard",
        "toColumn": "Broad Product Category"
      }
    ]
  }
}
